# prometheus/prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "nextjs"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["host.docker.internal:3000"]
    scrape_interval: 5s
    scrape_timeout: 5s
    honor_labels: true # Důležité pro zachování našich labelů
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "blog_.*"
        action: keep
